## Intro to Dataframes

In [15]:
import pandas as pd

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['A','B','C'], index=['a','b','c'])

print(df)

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [16]:
df.head()

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [17]:
print(df.tail())
print(df.describe())
print(df.info())
print(df.columns)
print(df.index)
print(df.dtypes)
print(df.shape)
print(df.values)
print(df.T)
print(df.to_numpy())
print(df.to_dict())
print(df.to_string(index=False))
print(df.to_csv(index=False))
# print(df.to_json(orient='records'))
# print(df.to_html(index=False))
# print(df.to_markdown(index=False))
# print(df.to_latex(index=False))
print(df.to_clipboard(index=False))
# print(df.to_excel('output.xlsx', index=False))

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9
         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes
None
Index(['A', 'B', 'C'], dtype='object')
Index(['a', 'b', 'c'], dtype='object')
A    int64
B    int64
C    int64
dtype: object
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
   a  b  c
A  1  4  7
B  2  5  8
C  3  6  9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
{'A': {'a': 1, 'b': 4, 'c': 7}, 'B': {'a': 2, 'b': 5, 'c': 8}, 'C': {'a': 3, 'b': 6, 'c': 9}}
 A  B  C
 1  2  3
 4  5  6
 7  8  9
A,B,C
1,2,3
4,5,6
7,8,9

None

In [ ]:
df.index
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

## Loading in Dataframes from files

In [23]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [25]:
results = pd.read_parquet('./data/results.parquet')
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None